apiVersion: v1
kind: Service
metadata:
  name: consumesafe-service
spec:
  type: NodePort
  selector:
    app: consumesafe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30669

