apiVersion: v1
kind: Service
metadata:
  name: boycottchecker-service
spec:
  type: NodePort
  selector:
    app: boycottchecker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30669

